In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:13].values
Y = dataset.iloc[:,13].values
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
dataset.shape

(10000, 14)

In [5]:
X.shape

(10000, 10)

In [6]:
Y.shape

(10000,)

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

In [9]:
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [10]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [11]:
X.shape

(10000, 12)

In [12]:
X = X[:,1:]

In [13]:
X.shape

(10000, 11)

In [14]:
print(X)

[[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 42)

In [16]:
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [18]:
classifier = Sequential()

In [19]:
classifier.add(Dense(units=6, kernel_initializer = 'uniform',activation = 'relu', input_dim = 11))

In [20]:
classifier.add(Dense(units=6, kernel_initializer = 'uniform',activation = 'relu'))

In [21]:
classifier.add(Dense(units=1, kernel_initializer = 'uniform',activation ='sigmoid'))

In [22]:
classifier.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics =['accuracy'])

In [ ]:
classifier.fit(X_train,Y_train, batch_size =10, epochs = 250)

Epoch 1/250
8000/8000 [==============================] - 4s 528us/step - loss: 0.4856 - acc: 0.7945
Epoch 2/250
8000/8000 [==============================] - 1s 107us/step - loss: 0.4293 - acc: 0.7945
Epoch 3/250
8000/8000 [==============================] - 1s 107us/step - loss: 0.4238 - acc: 0.7974
Epoch 4/250
8000/8000 [==============================] - 1s 126us/step - loss: 0.4206 - acc: 0.8231
Epoch 5/250
8000/8000 [==============================] - 2s 220us/step - loss: 0.4181 - acc: 0.8289
Epoch 6/250
8000/8000 [==============================] - 1s 154us/step - loss: 0.4160 - acc: 0.8316
Epoch 7/250
8000/8000 [==============================] - 1s 167us/step - loss: 0.4144 - acc: 0.8326
Epoch 8/250
8000/8000 [==============================] - 1s 142us/step - loss: 0.4136 - acc: 0.8340
Epoch 9/250
8000/8000 [==============================] - 1s 141us/step - loss: 0.4123 - acc: 0.8340
Epoch 10/250
8000/8000 [==============================] - 1s 142us/step - loss: 0.4116 - acc: 0.8334

8000/8000 [==============================] - 1s 154us/step - loss: 0.3991 - acc: 0.8375
Epoch 83/250
8000/8000 [==============================] - 1s 166us/step - loss: 0.3986 - acc: 0.8362
Epoch 84/250
8000/8000 [==============================] - 1s 151us/step - loss: 0.3985 - acc: 0.8369
Epoch 85/250
8000/8000 [==============================] - 1s 150us/step - loss: 0.3982 - acc: 0.8355
Epoch 86/250
8000/8000 [==============================] - 1s 144us/step - loss: 0.3985 - acc: 0.8352
Epoch 87/250
8000/8000 [==============================] - 1s 142us/step - loss: 0.3981 - acc: 0.8361
Epoch 88/250
8000/8000 [==============================] - 1s 131us/step - loss: 0.3981 - acc: 0.8364
Epoch 89/250
8000/8000 [==============================] - 1s 133us/step - loss: 0.3976 - acc: 0.8357
Epoch 90/250
8000/8000 [==============================] - ETA: 0s - loss: 0.3999 - acc: 0.835 - 1s 134us/step - loss: 0.3974 - acc: 0.8365
Epoch 91/250
8000/8000 [==============================] - 1s 145us

8000/8000 [==============================] - 1s 171us/step - loss: 0.3945 - acc: 0.8387
Epoch 163/250
8000/8000 [==============================] - 1s 163us/step - loss: 0.3943 - acc: 0.8409
Epoch 164/250
8000/8000 [==============================] - 1s 159us/step - loss: 0.3938 - acc: 0.8380
Epoch 165/250
8000/8000 [==============================] - 1s 161us/step - loss: 0.3945 - acc: 0.8387
Epoch 166/250
8000/8000 [==============================] - 1s 167us/step - loss: 0.3937 - acc: 0.8387
Epoch 167/250
8000/8000 [==============================] - 1s 142us/step - loss: 0.3947 - acc: 0.8377
Epoch 168/250
8000/8000 [==============================] - 1s 137us/step - loss: 0.3942 - acc: 0.8386
Epoch 169/250
8000/8000 [==============================] - 1s 147us/step - loss: 0.3941 - acc: 0.8402
Epoch 170/250
8000/8000 [==============================] - 1s 165us/step - loss: 0.3942 - acc: 0.8381
Epoch 171/250
8000/8000 [==============================] - 1s 151us/step - loss: 0.3940 - acc: 0

In [28]:
pred_y = classifier.predict(X_test)
pred_y = (pred_y>0.5)

In [29]:
print(pred_y)

[[False]
 [False]
 [False]
 ...
 [ True]
 [False]
 [False]]


In [30]:
score = classifier.evaluate(X_test,Y_test)
score

2000/2000 [==============================] - 0s 60us/step


[0.38794395232200624, 0.8405]