In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
def deriv(x):
    return x*(1-x)

In [6]:
x = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

In [7]:
y =np.array([[0],
            [1],
            [1],
            [0]])

In [8]:
alphas = [0.001,0.01,0.1,1,10,100,1000]

In [18]:
for alpha in alphas:
    print("\nTraining With Alpha ="+str(alpha))
    np.random.seed(1)
    #print(np.random.random((1,1)))
    synapse_0 = np.random.random((3,4))-1
    synapse_1 = np.random.random((4,1))-1
    
    for j in range(60000):
        layer_0 = x
        layer_1 = sigmoid(np.dot(layer_0,synapse_0))
        layer_2 = sigmoid(np.dot(layer_1,synapse_1))
        
        layer_2_error = layer_2 - y
        
        if j%1000==0:
            print("Error after "+str(j)+" iteration = "+str(np.mean(np.abs(layer_2_error))))
            
        layer_2_delta = layer_2_error*deriv(layer_2)
        
        layer_1_error = layer_2_delta.dot(synapse_1.T)
        
        layer_1_delta = layer_1_error*deriv(layer_1)
        
        synapse_1 -= alpha*(layer_1.T.dot(layer_2_delta))
        synapse_0 -= alpha*(layer_0.T.dot(layer_1_delta))
        
    
    


Training With Alpha =0.001
Error after 0 iteration = 0.4939887217823547
Error after 1000 iteration = 0.4938449572911151
Error after 2000 iteration = 0.4937401019467779
Error after 3000 iteration = 0.49366433033823953
Error after 4000 iteration = 0.49360980233297036
Error after 5000 iteration = 0.49357030866047724
Error after 6000 iteration = 0.49354095888323746
Error after 7000 iteration = 0.4935179184115342
Error after 8000 iteration = 0.493498192542968
Error after 9000 iteration = 0.49347945193648374
Error after 10000 iteration = 0.4934598929634791
Error after 11000 iteration = 0.493438126636646
Error after 12000 iteration = 0.49341309057306704
Error after 13000 iteration = 0.4933839793368764
Error after 14000 iteration = 0.49335018935908137
Error after 15000 iteration = 0.4933112753800463
Error after 16000 iteration = 0.49326691598611244
Error after 17000 iteration = 0.49321688632141264
Error after 18000 iteration = 0.49316103646379394
Error after 19000 iteration = 0.49309927427678

Error after 50000 iteration = 0.01749612744896197
Error after 51000 iteration = 0.017261863001993446
Error after 52000 iteration = 0.017036236228672
Error after 53000 iteration = 0.01681873546228378
Error after 54000 iteration = 0.01660889023005815
Error after 55000 iteration = 0.016406267100162596
Error after 56000 iteration = 0.016210466028109542
Error after 57000 iteration = 0.016021117133211003
Error after 58000 iteration = 0.015837877846592522
Error after 59000 iteration = 0.01566043038126211

Training With Alpha =1
Error after 0 iteration = 0.4939887217823547
Error after 1000 iteration = 0.1646222341816191
Error after 2000 iteration = 0.03711681059616398
Error after 3000 iteration = 0.02553648687026926
Error after 4000 iteration = 0.020481022453932643
Error after 5000 iteration = 0.017505414409564733
Error after 6000 iteration = 0.015495951869749485
Error after 7000 iteration = 0.014025469948475486
Error after 8000 iteration = 0.012890954942113592
Error after 9000 iteration = 0.0

Error after 34000 iteration = 0.125302769107849
Error after 35000 iteration = 0.12529893051837646
Error after 36000 iteration = 0.12529524118452187
Error after 37000 iteration = 0.1252916913156209
Error after 38000 iteration = 0.12528827200481754
Error after 39000 iteration = 0.12528497512871936
Error after 40000 iteration = 0.12528179326064676
Error after 41000 iteration = 0.12527871959535222
Error after 42000 iteration = 0.12527574788345702
Error after 43000 iteration = 0.12527287237415738
Error after 44000 iteration = 0.12527008776499304
Error after 45000 iteration = 0.1252673891576731
Error after 46000 iteration = 0.12526477201911232
Error after 47000 iteration = 0.12526223214696802
Error after 48000 iteration = 0.12525976563907393
Error after 49000 iteration = 0.12525736886626204
Error after 50000 iteration = 0.12525503844813582
Error after 51000 iteration = 0.1252527712314237
Error after 52000 iteration = 0.12525056427059464
Error after 53000 iteration = 0.12524841481045987
Error

In [15]:
print(synapse_0)

[[-0.582978   -0.27967551 -0.99988563 -0.69766743]
 [-0.85324411 -0.90766141 -0.81373979 -0.65443927]
 [-0.60323253 -0.46118327 -0.58080549 -0.3147805 ]]


In [16]:
print(synapse_1)

[[-0.79554775]
 [-0.12188256]
 [-0.97261241]
 [-0.32953249]]
